### ISSUE TITLE
getCaptcha failing

### ISSUE THREAD

**Issue by deanpetrovic** [marten-seemann/OXID_recaptcha#3]
All of a sudden with no changes, we are seeing the following error in the controller?  Any ideas?

2022-09-15 10:43:03] OXID Logger.ERROR: Function 'getCaptcha' does not exist or is not accessible!
(OxidEsales\GdprOptinModule\Controller\ContactController)
 ["[object] (OxidEsales\\Eshop\\Core\\Exception\\SystemComponentException(code: 0):
 Function 'getCaptcha' does not exist or is not accessible! (OxidEs
 ales\\GdprOptinModule\\Controller\\ContactController)\n

**Comment by marten-seemann** [comment]
No idea, sorry!
